development:
  sessions:
    default:
      database: people_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    devices:
      database: devices_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    # set opptions
test:
  sessions:
    default:
      database: people_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    devices:
      database: devices_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    # set opptions
