development:
  sessions:
    default:
      database: locations_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    devices:
      database: devices_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    jobs:
      database: jobs_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    # set opptions
test:
  sessions:
    default:
      database: locations_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    devices:
      database: devices_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    jobs:
      database: jobs_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    # set opptions
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_LOCATIONS_URL'] %>
    people:
      uri: <%= ENV['MONGOLAB_PEOPLE_URL'] %>
    devices:
      uri: <%= ENV['MONGOLAB_DEVICES_URL'] %>
    jobs:
      uri: <%= ENV['MONGOLAB_JOBS_URL'] %>
  options:
