pagination:
  per: 25
  max_per: 100
locations:
  types:
    - 'house'
    - 'floor'
    - 'room'
scopes:
  read:
    - resources
    - resources-read
    - locations
    - locations-read
  write:
    - resources
    - locations
