device:
  host: <%= device_host = "https://device.lelylan.com" %>
  uri: <%= "#{device_host}/devices/closet-dimmer" %>
  another:
    uri: <%= "#{device_host}/devices/another-closet-dimmer" %>
  descendants:
    uri: <%= "#{device_host}/devices/descendant-closet-dimmer" %>

type:
  host: <%= type_host = "https://type.lelylan.com" %>
  uri: <%= "#{type_host}/types/dimmer" %>
  another:
    uri: <%= "#{type_host}/types/another-dimmer" %>

user: 
  email:    'alice@example.com'
  password: 'example'
  id:       <%= Moped::BSON::ObjectId('500fb2d4d033a95185000001') %>
  another:
    email: 'bob@example.com'
    id:    <%= Moped::BSON::ObjectId('500fb2d4d033a95185000002') %>

validation:
  uris:
    valid: ['http://example.com', 'http://www.examle.com']
    not_valid: ['example', 'example.com', 'www.example.com']

